import Header from '@/components/Header'
import './globals.css'
import { Saira_Stencil_One } from 'next/font/google'
import Footer from '@/components/Footer'

const logo = Saira_Stencil_One({ 
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable:'--font-logo',
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={logo.variable}>
      <body>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
